#!/usr/bin/bash

CFG_FLAGS=("-DCMAKE_BUILD_TYPE=$BUILD_TYPE" '-DBUILD_SHARED_LIBS=YES' '-DVCPKG_CMAKE_SYSTEM_NAME=Android' '-DCMAKE_SYSTEM_NAME=Android' "-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake")
cd "$PROJECT_ROOT"
cmake -B $PROJECT_ROOT/build-$TRIPLET -DVCPKG_TARGET_TRIPLET=$TRIPLET -DANDROID_ABI=$ABI "${CFG_FLAGS[@]}"
cmake --build $PROJECT_ROOT/build-$TRIPLET --config $BUILD_TYPE
