name: ci-darwin

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  build-darwin:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        targets: |
          x86_64-apple-darwin
          aarch64-apple-darwin
          aarch64-apple-ios

    - name: Build macOS (x86_64-apple-darwin)
      if: '!cancelled()'
      run: |
        cargo build --manifest-path Native/Cargo.toml -p uniasset --release --target x86_64-apple-darwin

    - name: Build macOS (aarch64-apple-darwin)
      if: '!cancelled()'
      run: |
        cargo build --manifest-path Native/Cargo.toml -p uniasset --release --target aarch64-apple-darwin

    - name: Build iOS (aarch64-apple-ios)
      if: '!cancelled()'
      run: |
        cargo build --manifest-path Native/Cargo.toml -p uniasset --release --target aarch64-apple-ios


    - name: Upload Artifact (x64-osx)
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: libuniasset-x64-osx
        path: ${{github.workspace}}/Native/target/x86_64-apple-darwin/release/libuniasset.dylib

    - name: Upload Artifact (arm64-osx)
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: libuniasset-arm64-osx
        path: ${{github.workspace}}/Native/target/aarch64-apple-darwin/release/libuniasset.dylib

    - name: Upload Artifact (arm64-ios)
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: libuniasset-arm64-ios
        path: ${{github.workspace}}/Native/target/aarch64-apple-ios/release/libuniasset.a
