name: 'Build (Linux)'

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-gnu
        components: rust-src

    - name: Build (x86_64-unknown-linux-gnu)
      run: |
        cargo build --manifest-path Native/Cargo.toml --release --target x86_64-unknown-linux-gnu -Z build-std=std,panic_abort

    - name: Upload Artifact (x64-linux)
      uses: actions/upload-artifact@v4
      with:
        name: libuniasset-x64-linux
        path: ${{github.workspace}}/Native/target/x86_64-unknown-linux-gnu/release/libuniasset.so
