name: 'Build (Windows)'

on:
  workflow_dispatch: {}
  workflow_call: {}


jobs:
  build-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v8

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-pc-windows-msvc
        components: rust-src

    - name: Build (x86_64-pc-windows-msvc)
      run: |
        cargo build --manifest-path Native/Cargo.toml --release --target x86_64-pc-windows-msvc -Z build-std=std,panic_abort

    - name: Upload Artifact (x64-windows)
      if: '!cancelled()'
      uses: actions/upload-artifact@v7
      with:
        name: uniasset-x64-windows
        path: ${{github.workspace}}/Native/target/x86_64-pc-windows-msvc/release/*.dll
