name: releasing

on: 
  push:
    tags: [ 'v*.*.*' ]

env:
  BUILD_TYPE: Release

jobs:
  build-win:
    uses: ./.github/workflows/ci-windows.yml

  build-linux:
    uses: ./.github/workflows/ci-linux.yml

  build-darwin:
    uses: ./.github/workflows/ci-darwin.yml

  build-android:
    uses: ./.github/workflows/ci-android.yml

  releasing:
    runs-on: ubuntu-latest
    needs: ['build-win', 'build-linux', 'build-darwin', 'build-android']
    if: '!cancelled()'

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: 'outputs/'

      - name: Zipping all things
        if: '!cancelled()'
        run: |
          zip -r "${{github.workspace}}/output.zip" "${{github.workspace}}/outputs/*"

      - name: Package unity scripts
        if: '!cancelled()'
        run: |
          zip -r "${{github.workspace}}/Unity/UnityScripts.zip" "${{github.workspace}}/Unity/UniassetTest/Assets/Plugins/"

      - name: Upload binaries to release
        if: '!cancelled()'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{github.workspace}}/output.zip"
          asset_name: "uniasset-native-libraries.zip"

      - name: Upload unity scripts
        if: '!cancelled()'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{github.workspace}}/Unity/UnityScripts.zip"
          asset_name: "uniasset-unity-scripts.zip"
