name: releasing

on: 
  push:
    tags: [ 'v*.*.*' ]

env:
  BUILD_TYPE: Release

jobs:
  build-win:
    uses: ./.github/workflows/ci-windows.yml

  build-linux:
    uses: ./.github/workflows/ci-linux.yml

  build-darwin:
    uses: ./.github/workflows/ci-darwin.yml

  build-android:
    uses: ./.github/workflows/ci-android.yml

  releasing:
    runs-on: ubuntu-latest
    needs: ['build-win', 'build-linux', 'build-darwin', 'build-android']
    if: '!cancelled()'

    steps:
      - uses: actions/checkout@v3

      - name: Download libuniasset-x64-osx.dylib
        uses: dawidd6/action-download-artifact@v6
        with:
          name: libuniasset-x64-osx.dylib
          path: 'outputs/libuniasset-x64-osx/'
          run_id:  ${{ github.event.workflow_run.id }}

      - name: Download libuniasset-x64-osx.dylib
        uses: dawidd6/action-download-artifact@v6
        with:
          name: libuniasset-arm64-osx.dylib
          path: 'outputs/libuniasset-arm64-osx/'
          run_id:  ${{ github.event.workflow_run.id }}

      - name: Download libuniasset-arm64-ios-bitcode.a
        uses: dawidd6/action-download-artifact@v6
        with:
          name: libuniasset-arm64-ios-bitcode.a
          path: 'outputs/libuniasset-arm64-ios-bitcode/'
          run_id:  ${{ github.event.workflow_run.id }}

      - name: Download libuniasset-arm-neon-android.so
        uses: dawidd6/action-download-artifact@v6
        with:
          name: libuniasset-arm-neon-android.so
          path: 'outputs/libuniasset-arm-neon-android/'
          run_id:  ${{ github.event.workflow_run.id }}

      - name: Download libuniasset-arm64-android.so
        uses: dawidd6/action-download-artifact@v6
        with:
          name: libuniasset-arm64-android.so
          path: 'outputs/libuniasset-arm64-android/'
          run_id:  ${{ github.event.workflow_run.id }}

      - name: Download libuniasset-x86-android.so
        uses: dawidd6/action-download-artifact@v6
        with:
          name: libuniasset-x86-android.so
          path: 'outputs/libuniasset-x86-android/'
          run_id:  ${{ github.event.workflow_run.id }}

      - name: Download libuniasset-x64-android.so
        uses: dawidd6/action-download-artifact@v6
        with:
          name: libuniasset-x64-android.so
          path: 'outputs/libuniasset-x64-android/'
          run_id:  ${{ github.event.workflow_run.id }}

      - name: Download uniasset-x64-windows.dll
        uses: dawidd6/action-download-artifact@v6
        with:
          name: uniasset-x64-windows.dll
          path: 'outputs/uniasset-x64-windows/'
          run_id:  ${{ github.event.workflow_run.id }}

      - name: Download uniasset-x86-windows.dll
        uses: dawidd6/action-download-artifact@v6
        with:
          name: uniasset-x86-windows.dll
          path: 'outputs/uniasset-x86-windows/'
          run_id:  ${{ github.event.workflow_run.id }}


      - name: Download libuniasset-x64-linux.so
        uses: dawidd6/action-download-artifact@v6
        with:
          name: libuniasset-x64-linux.so
          path: 'outputs/libuniasset-x64-linux/'
          run_id:  ${{ github.event.workflow_run.id }}

      - name: Zipping all things
        run: |
          zip -r "${{github.workspace}}/output.zip" "${{github.workspace}}/outputs/*"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{github.workspace}}/output.zip"
          asset_name: "uniasset-native-libraries.zip"

      - name: Package unity scripts
        run: |
          zip -r "${{github.workspace}}/Unity/UnityScripts.zip" "${{github.workspace}}/Unity/UniassetTest/Assets/Plugins/"

      - name: Upload unity scripts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{github.workspace}}/Unity/UnityScripts.zip"
          asset_name: "uniasset-unity-scripts.zip"
